header:
  specformat: "1.0"

spec:
  database:
    host: localhost
    port: 5432
    name: pdb
    user: root
    pass: root
  portal:
    base_url: http://localhost:8080
    quotecalc_url: quotecalc
 